apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello Piyush</title>
    </head>
    <body>
        <h1>Hello Piyush</h1>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: hello-piyush-html
